language: python
python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install --upgrade setuptools
  - pip install "pip<19.0"
  - pip install  .
  - pip install  --upgrade pycodestyle pylint pytest pytest-cov coveralls

script:
  - pycodestyle invirtualenv
  - pylint invirtualenv
  - pytest --cov=invirtualenv --cov-report=xml:cobertura.xml --cov-report term-missing tests/

matrix:
  fast_finish: true

after_success:
  coveralls

notifications:
  irc:
    channels: "irc.freenode.org#invirtualenv"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
